module.exports = {
  reactStrictMode: true,
}

NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY="AIzaSyBIxhYJHsUoMxTPZ-Rm-WgsMBCfSE-ZCok"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="rate-my-accommodation.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="rate-my-accommodation"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="rate-my-accommodation.appspot.com"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="551364748132"
NEXT_PUBLIC_FIREBASE_APP_ID="1:551364748132:web:33a93b0b0aecdd8c361071"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-6XM36N35K3"
